version: "3.9"

services:
  street-side-api:
    build:
      context: ../../
      dockerfile: ./street-side/street-side-api/docker/Dockerfile
      target: development
    ports:
      - "8080:8080"
    volumes:
      - ../street-side-api/street_side_api:/opt/street-side/street-side-api/street_side_api
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - RELOAD=true
      - LOG_CONFIG=/opt/street-side/street-side-api/street_side_api/log_config.json
      - WORKERS=1
      - ASYNCPG_MIN_POOL_SIZE=20
      - ASYNCPG_MAX_POOL_SIZE=20
      - ENVIRONMENT=LOCAL
    entrypoint:
      [
        "/bin/sh",
        "/opt/street-side/street-side-api/docker/entrypoint.sh"
      ]
