version: "3.9"

services:
  postgres:
    image: postgres:14.5-alpine3.16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=street-side
    volumes:
      - ../datastore/postgres/:/var/lib/postgresql/data
    healthcheck:
      test: /bin/sh -c 'pg_isready -U postgres -d postgres || exit 1'
      interval: 5s
      timeout: 60s
      retries: 12
    ports:
      - "5432:5432"
  street-side-api:
    build:
      context: ../../
      dockerfile: ./street-side/street-side-api/docker/Dockerfile
      target: development
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: /bin/sh -c "curl localhost:8080/health/"
      timeout: 60s
      retries: 1
    ports:
      - "8080:8080"
    volumes:
      - ../configuration:/opt/street-side/configuration
      - ../datastore/storage:/opt/street-side/datastore/storage
      - ../street-side-api/street_side_api:/opt/street-side/street-side-api/street_side_api
    environment:
      - STREET_SIDE_CONFIGURATION_PATH=/opt/street-side/configuration/docker_prod.json
      - HOST=0.0.0.0
      - PORT=8080
      - RELOAD=true
      - LOG_CONFIG=/opt/street-side/street-side-api/street_side_api/log_config.json
      - WORKERS=1
      - POSTGRES_DSN=${POSTGRES_DSN}
      - ASYNCPG_MIN_POOL_SIZE=20
      - ASYNCPG_MAX_POOL_SIZE=20
      - ENVIRONMENT=LOCAL
    entrypoint:
      [
        "/bin/sh",
        "/opt/street-side/street-side-api/docker/entrypoint.sh"
      ]

  street-side-frontend:
    build:
      context: ../../
      dockerfile: ./street-side/street-side-frontend/docker/Dockerfile
      target: development
    depends_on:
      street-side-api:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ../street-side-frontend/.next:/opt/street-side/street-side-frontend/.next
      - ../street-side-frontend/app:/opt/street-side/street-side-frontend/app
      - ../street-side-frontend/api:/opt/street-side/street-side-frontend/api
